Repository auth0/java-jwt, pull requests merged in 2020-02, with the labels that each got.

#381 Allow to customize the typ header claim
  lib/src/main/java/com/auth0/jwt/JWTCreator.java
  lib/src/test/java/com/auth0/jwt/JWTCreatorTest.java
Labels: CH: Added, small

#382 Add Javadoc URL and badge to the README
  README.md
Labels: CH: Added, tiny

#387 Use JDK 8
  lib/build.gradle
Labels: tiny

#386 Update tests to use valid Base64 URL-encoded tokens
  lib/src/test/java/com/auth0/jwt/algorithms/ECDSAAlgorithmTest.java
Labels: tiny

#389 Update to Gradle 6.1.1
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  lib/build.gradle
Labels: CH: Changed, small

#282 JWTCreator for basic types
  lib/src/main/java/com/auth0/jwt/JWTCreator.java
  lib/src/test/java/com/auth0/jwt/JWTCreatorTest.java
Labels: medium

#393 Handle missing expected array claim
  lib/src/main/java/com/auth0/jwt/JWTCreator.java
  lib/src/main/java/com/auth0/jwt/JWTVerifier.java
  lib/src/main/java/com/auth0/jwt/interfaces/JWTVerifier.java
  lib/src/test/java/com/auth0/jwt/JWTCreatorTest.java
  lib/src/test/java/com/auth0/jwt/JWTVerifierTest.java
Labels: small

#394 Release 3.10.0
  CHANGELOG.md
  README.md
Labels: tiny

#399 Update jackson-databind to 2.10.2
  lib/build.gradle
Labels: CH: Security
