Repository auth0/java-jwt, pull requests merged in 2020-12, with the labels that each got.

#462 Thread-safe classes should be Shared statically
  lib/src/main/java/com/auth0/jwt/JWTCreator.java
Labels: CH: Changed

#455 Target Java 8
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  lib/build.gradle
  settings.gradle
Labels: CH: Breaking Change

#465 Release 3.12.0
  CHANGELOG.md
  README.md
Labels: review:tiny
