Repository auth0/java-jwt, pull requests merged in 2020-03, with the labels that each got.

#402 Remove unneeded null check
  lib/src/main/java/com/auth0/jwt/JWTCreator.java
Labels: CH: Fixed

#398 Refactoring
  lib/src/main/java/com/auth0/jwt/ClockImpl.java
  lib/src/main/java/com/auth0/jwt/JWT.java
  lib/src/main/java/com/auth0/jwt/JWTCreator.java
  lib/src/main/java/com/auth0/jwt/JWTDecoder.java
  lib/src/main/java/com/auth0/jwt/JWTVerifier.java
  lib/src/main/java/com/auth0/jwt/TokenUtils.java
  lib/src/main/java/com/auth0/jwt/algorithms/Algorithm.java
  lib/src/main/java/com/auth0/jwt/algorithms/CryptoHelper.java
  lib/src/main/java/com/auth0/jwt/algorithms/ECDSAAlgorithm.java
  lib/src/main/java/com/auth0/jwt/algorithms/HMACAlgorithm.java
  lib/src/main/java/com/auth0/jwt/algorithms/RSAAlgorithm.java
  lib/src/main/java/com/auth0/jwt/exceptions/AlgorithmMismatchException.java
  lib/src/main/java/com/auth0/jwt/exceptions/InvalidClaimException.java
  lib/src/main/java/com/auth0/jwt/exceptions/JWTCreationException.java
  lib/src/main/java/com/auth0/jwt/exceptions/JWTDecodeException.java
  lib/src/main/java/com/auth0/jwt/exceptions/JWTVerificationException.java
  lib/src/main/java/com/auth0/jwt/exceptions/SignatureGenerationException.java
  lib/src/main/java/com/auth0/jwt/exceptions/SignatureVerificationException.java
  lib/src/main/java/com/auth0/jwt/exceptions/TokenExpiredException.java
  lib/src/main/java/com/auth0/jwt/impl/HeaderDeserializer.java
  lib/src/main/java/com/auth0/jwt/impl/JsonNodeClaim.java
  lib/src/main/java/com/auth0/jwt/impl/PayloadDeserializer.java
  lib/src/main/java/com/auth0/jwt/impl/PayloadImpl.java
  lib/src/main/java/com/auth0/jwt/impl/PayloadSerializer.java
  lib/src/main/java/com/auth0/jwt/impl/PublicClaims.java
  lib/src/main/java/com/auth0/jwt/interfaces/Claim.java
  lib/src/main/java/com/auth0/jwt/interfaces/Clock.java
  lib/src/main/java/com/auth0/jwt/interfaces/ECDSAKeyProvider.java
  lib/src/main/java/com/auth0/jwt/interfaces/Header.java
  lib/src/main/java/com/auth0/jwt/interfaces/JWTPartsParser.java
  lib/src/main/java/com/auth0/jwt/interfaces/JWTVerifier.java
  lib/src/main/java/com/auth0/jwt/interfaces/KeyProvider.java
  lib/src/main/java/com/auth0/jwt/interfaces/Payload.java
  lib/src/main/java/com/auth0/jwt/interfaces/RSAKeyProvider.java
  lib/src/test/java/com/auth0/jwt/ClockImplTest.java
  lib/src/test/java/com/auth0/jwt/ConcurrentVerifyTest.java
  lib/src/test/java/com/auth0/jwt/JWTCreatorTest.java
  lib/src/test/java/com/auth0/jwt/JWTDecoderTest.java
  lib/src/test/java/com/auth0/jwt/JWTTest.java
  lib/src/test/java/com/auth0/jwt/JWTVerifierTest.java
  lib/src/test/java/com/auth0/jwt/JsonMatcher.java
  lib/src/test/java/com/auth0/jwt/PemUtils.java
  lib/src/test/java/com/auth0/jwt/TokenUtilsTest.java
  lib/src/test/java/com/auth0/jwt/UserPojo.java
  lib/src/test/java/com/auth0/jwt/algorithms/AlgorithmTest.java
  lib/src/test/java/com/auth0/jwt/algorithms/CryptoTestHelper.java
  lib/src/test/java/com/auth0/jwt/algorithms/ECDSAAlgorithmTest.java
  lib/src/test/java/com/auth0/jwt/algorithms/ECDSABouncyCastleProviderTests.java
  lib/src/test/java/com/auth0/jwt/algorithms/HMACAlgorithmTest.java
  lib/src/test/java/com/auth0/jwt/algorithms/NoneAlgorithmTest.java
  lib/src/test/java/com/auth0/jwt/algorithms/RSAAlgorithmTest.java
  lib/src/test/java/com/auth0/jwt/impl/BasicHeaderTest.java
  lib/src/test/java/com/auth0/jwt/impl/ClaimsHolderTest.java
  lib/src/test/java/com/auth0/jwt/impl/HeaderDeserializerTest.java
  lib/src/test/java/com/auth0/jwt/impl/JWTParserTest.java
  lib/src/test/java/com/auth0/jwt/impl/JsonNodeClaimTest.java
  lib/src/test/java/com/auth0/jwt/impl/NullClaimTest.java
  lib/src/test/java/com/auth0/jwt/impl/PayloadDeserializerTest.java
  lib/src/test/java/com/auth0/jwt/impl/PayloadImplTest.java
  lib/src/test/java/com/auth0/jwt/impl/PayloadSerializerTest.java
Labels: CH: Changed

#392 Updated date time APIs
  README.md
  lib/src/main/java/com/auth0/jwt/ClockImpl.java
  lib/src/main/java/com/auth0/jwt/JWTCreator.java
  lib/src/main/java/com/auth0/jwt/JWTDecoder.java
  lib/src/main/java/com/auth0/jwt/JWTVerifier.java
  lib/src/main/java/com/auth0/jwt/impl/JsonNodeClaim.java
  lib/src/main/java/com/auth0/jwt/impl/NullClaim.java
  lib/src/main/java/com/auth0/jwt/impl/PayloadDeserializer.java
  lib/src/main/java/com/auth0/jwt/impl/PayloadImpl.java
  lib/src/main/java/com/auth0/jwt/impl/PayloadSerializer.java
  lib/src/main/java/com/auth0/jwt/interfaces/Claim.java
  lib/src/main/java/com/auth0/jwt/interfaces/Clock.java
  lib/src/main/java/com/auth0/jwt/interfaces/Payload.java
  lib/src/main/java/com/auth0/jwt/interfaces/Verification.java
  lib/src/test/java/com/auth0/jwt/ClockImplTest.java
  lib/src/test/java/com/auth0/jwt/JWTCreatorTest.java
  lib/src/test/java/com/auth0/jwt/JWTDecoderTest.java
  lib/src/test/java/com/auth0/jwt/JWTTest.java
  lib/src/test/java/com/auth0/jwt/JWTVerifierTest.java
  lib/src/test/java/com/auth0/jwt/impl/JsonNodeClaimTest.java
  lib/src/test/java/com/auth0/jwt/impl/NullClaimTest.java
  lib/src/test/java/com/auth0/jwt/impl/PayloadDeserializerTest.java
  lib/src/test/java/com/auth0/jwt/impl/PayloadImplTest.java
  lib/src/test/java/com/auth0/jwt/impl/PayloadSerializerTest.java
Labels: CH: Added, size: large

#401 Use java.util.Base64 for encoding and decoding
  lib/build.gradle
  lib/src/main/java/com/auth0/jwt/JWTCreator.java
  lib/src/main/java/com/auth0/jwt/JWTDecoder.java
  lib/src/main/java/com/auth0/jwt/algorithms/ECDSAAlgorithm.java
  lib/src/main/java/com/auth0/jwt/algorithms/HMACAlgorithm.java
  lib/src/main/java/com/auth0/jwt/algorithms/NoneAlgorithm.java
  lib/src/main/java/com/auth0/jwt/algorithms/RSAAlgorithm.java
  lib/src/test/java/com/auth0/jwt/JWTCreatorTest.java
  lib/src/test/java/com/auth0/jwt/JWTDecoderTest.java
  lib/src/test/java/com/auth0/jwt/JWTTest.java
  lib/src/test/java/com/auth0/jwt/algorithms/CryptoTestHelper.java
  lib/src/test/java/com/auth0/jwt/algorithms/ECDSAAlgorithmTest.java
  lib/src/test/java/com/auth0/jwt/algorithms/ECDSABouncyCastleProviderTests.java
  lib/src/test/java/com/auth0/jwt/algorithms/HMACAlgorithmTest.java
  lib/src/test/java/com/auth0/jwt/algorithms/NoneAlgorithmTest.java
  lib/src/test/java/com/auth0/jwt/algorithms/RSAAlgorithmTest.java
Labels: CH: Changed, size: large

#403 Deprecate Date and array based claim methods
  lib/src/main/java/com/auth0/jwt/JWTCreator.java
  lib/src/main/java/com/auth0/jwt/interfaces/Claim.java
  lib/src/main/java/com/auth0/jwt/interfaces/Clock.java
  lib/src/main/java/com/auth0/jwt/interfaces/Payload.java
  lib/src/main/java/com/auth0/jwt/interfaces/Verification.java
Labels: CH: Deprecated, size: small

#406 Fix date serialization for list/map claims
  lib/src/main/java/com/auth0/jwt/impl/PayloadSerializer.java
  lib/src/test/java/com/auth0/jwt/JWTCreatorTest.java
Labels: size: small

#407 Update Jackson and Commons Codec dependencies
  lib/build.gradle
Labels: CH: Changed, size: tiny

#408 Release 3.10.1
  CHANGELOG.md
  README.md
Labels: size: tiny

#412 Check varargs null values in JWTVerifier
  lib/src/main/java/com/auth0/jwt/JWTVerifier.java
  lib/src/test/java/com/auth0/jwt/JWTVerifierTest.java
Labels: CH: Fixed, small

#413 JavaDoc fix
  lib/src/main/java/com/auth0/jwt/interfaces/Verification.java
Labels: CH: Fixed, documentation, tiny

#414 Release 3.10.2
  CHANGELOG.md
  README.md
Labels: tiny

#397 Feature/readme
  README.md
Labels: documentation, small
