Repository auth0/java-jwt, pull requests merged in 2021-01, with the labels that each got.

#464 Fix: updated jackson-databind to 2.11.0 to block CVE-2020-25649
  lib/build.gradle
Labels: waiting for customer

#468 Release 3.12.1
  CHANGELOG.md
  README.md
Labels: tiny

#469 Add toString to Claim objects [SDK-2225]
  lib/src/main/java/com/auth0/jwt/impl/JsonNodeClaim.java
  lib/src/main/java/com/auth0/jwt/impl/NullClaim.java
  lib/src/test/java/com/auth0/jwt/impl/JsonNodeClaimTest.java
  lib/src/test/java/com/auth0/jwt/impl/NullClaimTest.java
Labels: CH: Added, review:small
