Repository auth0/java-jwt, pull requests merged in 2021-04, with the labels that each got.

#482 Remove jcenter
  build.gradle
  settings.gradle
Labels: CH: Changed

#490 Release 3.15.0
  CHANGELOG.md
  README.md
Labels: review:tiny

#491 Update OSS plugin version
  settings.gradle
Labels: review:tiny

#493 Delete duplicated issue template
  .github/ISSUE_TEMPLATE/report_a_bug.md
Labels: review:small

#495 Add package-info.java for internal `impl` package
  .gitignore
  lib/src/main/java/com/auth0/jwt/impl/NullClaim.java
  lib/src/main/java/com/auth0/jwt/impl/package-info.java
  lib/src/main/java/com/auth0/jwt/interfaces/Header.java
  lib/src/main/java/com/auth0/jwt/interfaces/Payload.java
Labels: CH: Changed, documentation

#496 Improve Javadoc generation
  lib/build.gradle
Labels: CH: Changed, documentation
