Repository auth0/java-jwt, pull requests merged in 2022-03, with the labels that each got.

#530 Replace deprecated assertThat method in tests
  lib/src/test/java/com/auth0/jwt/ClockImplTest.java
  lib/src/test/java/com/auth0/jwt/JWTCreatorTest.java
  lib/src/test/java/com/auth0/jwt/JWTDecoderTest.java
  lib/src/test/java/com/auth0/jwt/JWTTest.java
  lib/src/test/java/com/auth0/jwt/JWTVerifierTest.java
  lib/src/test/java/com/auth0/jwt/TokenUtilsTest.java
  lib/src/test/java/com/auth0/jwt/algorithms/AlgorithmTest.java
  lib/src/test/java/com/auth0/jwt/algorithms/CryptoTestHelper.java
  lib/src/test/java/com/auth0/jwt/algorithms/ECDSAAlgorithmTest.java
  lib/src/test/java/com/auth0/jwt/algorithms/ECDSABouncyCastleProviderTests.java
  lib/src/test/java/com/auth0/jwt/algorithms/HMACAlgorithmTest.java
  lib/src/test/java/com/auth0/jwt/algorithms/NoneAlgorithmTest.java
  lib/src/test/java/com/auth0/jwt/algorithms/RSAAlgorithmTest.java
  lib/src/test/java/com/auth0/jwt/impl/ClaimsHolderTest.java
  lib/src/test/java/com/auth0/jwt/impl/HeaderDeserializerTest.java
  lib/src/test/java/com/auth0/jwt/impl/JsonNodeClaimTest.java
  lib/src/test/java/com/auth0/jwt/impl/NullClaimTest.java
  lib/src/test/java/com/auth0/jwt/impl/PayloadDeserializerTest.java
  lib/src/test/java/com/auth0/jwt/impl/PayloadSerializerTest.java
Labels: CH: Changed

#531 Remove apiDiff check for v4 development
  .circleci/config.yml
Labels: review:small

#532 [SDK-3160] Replace com.auth0.jwt.interfaces.Clock with java.time.Clock
  lib/src/main/java/com/auth0/jwt/JWTVerifier.java
  lib/src/test/java/com/auth0/jwt/JWTTest.java
  lib/src/test/java/com/auth0/jwt/JWTVerifierTest.java
Labels: CH: Breaking Change

#535 Test only change - remove unnecessary throws clause from tests
  lib/src/test/java/com/auth0/jwt/ConcurrentVerifyTest.java
  lib/src/test/java/com/auth0/jwt/JWTCreatorTest.java
  lib/src/test/java/com/auth0/jwt/JWTDecoderTest.java
  lib/src/test/java/com/auth0/jwt/JWTTest.java
  lib/src/test/java/com/auth0/jwt/JWTVerifierTest.java
  lib/src/test/java/com/auth0/jwt/TokenUtilsTest.java
  lib/src/test/java/com/auth0/jwt/algorithms/AlgorithmTest.java
  lib/src/test/java/com/auth0/jwt/algorithms/ECDSAAlgorithmTest.java
  lib/src/test/java/com/auth0/jwt/algorithms/ECDSABouncyCastleProviderTests.java
  lib/src/test/java/com/auth0/jwt/algorithms/HMACAlgorithmTest.java
  lib/src/test/java/com/auth0/jwt/algorithms/NoneAlgorithmTest.java
  lib/src/test/java/com/auth0/jwt/algorithms/RSAAlgorithmTest.java
  lib/src/test/java/com/auth0/jwt/impl/BasicHeaderTest.java
  lib/src/test/java/com/auth0/jwt/impl/ClaimsHolderTest.java
  lib/src/test/java/com/auth0/jwt/impl/HeaderDeserializerTest.java
  lib/src/test/java/com/auth0/jwt/impl/JWTParserTest.java
  lib/src/test/java/com/auth0/jwt/impl/JsonNodeClaimTest.java
  lib/src/test/java/com/auth0/jwt/impl/NullClaimTest.java
  lib/src/test/java/com/auth0/jwt/impl/PayloadDeserializerTest.java
  lib/src/test/java/com/auth0/jwt/impl/PayloadImplTest.java
Labels: CH: Fixed

#533 [SDK-3160] Remove internal Clock
  lib/src/main/java/com/auth0/jwt/ClockImpl.java
  lib/src/main/java/com/auth0/jwt/interfaces/Clock.java
  lib/src/test/java/com/auth0/jwt/ClockImplTest.java
Labels: CH: Removed, review:small

#534 [SDK-3150] Serialize dates in collections as seconds since epoch
  lib/src/main/java/com/auth0/jwt/JWTCreator.java
  lib/src/main/java/com/auth0/jwt/impl/PayloadSerializer.java
  lib/src/test/java/com/auth0/jwt/JWTCreatorTest.java
  lib/src/test/java/com/auth0/jwt/impl/PayloadSerializerTest.java
Labels: CH: Breaking Change, review:medium

#537 [SDK-3149] Add Instant support
  lib/src/main/java/com/auth0/jwt/JWTCreator.java
  lib/src/main/java/com/auth0/jwt/JWTDecoder.java
  lib/src/main/java/com/auth0/jwt/JWTVerifier.java
  lib/src/main/java/com/auth0/jwt/impl/JsonNodeClaim.java
  lib/src/main/java/com/auth0/jwt/impl/NullClaim.java
  lib/src/main/java/com/auth0/jwt/impl/PayloadDeserializer.java
  lib/src/main/java/com/auth0/jwt/impl/PayloadImpl.java
  lib/src/main/java/com/auth0/jwt/impl/PayloadSerializer.java
  lib/src/main/java/com/auth0/jwt/interfaces/Claim.java
  lib/src/main/java/com/auth0/jwt/interfaces/Payload.java
  lib/src/test/java/com/auth0/jwt/JWTCreatorTest.java
  lib/src/test/java/com/auth0/jwt/JWTDecoderTest.java
  lib/src/test/java/com/auth0/jwt/JWTTest.java
  lib/src/test/java/com/auth0/jwt/JWTVerifierTest.java
  lib/src/test/java/com/auth0/jwt/impl/JsonNodeClaimTest.java
  lib/src/test/java/com/auth0/jwt/impl/NullClaimTest.java
  lib/src/test/java/com/auth0/jwt/impl/PayloadDeserializerTest.java
  lib/src/test/java/com/auth0/jwt/impl/PayloadImplTest.java
  lib/src/test/java/com/auth0/jwt/interfaces/ClaimTest.java
  lib/src/test/java/com/auth0/jwt/interfaces/PayloadTest.java
Labels: CH: Added, review:large

#539 [SDK-3197] Update test deps
  lib/build.gradle
  lib/src/test/java/com/auth0/jwt/JWTDecoderTest.java
  lib/src/test/java/com/auth0/jwt/JWTTest.java
  lib/src/test/java/com/auth0/jwt/impl/PayloadDeserializerTest.java
  lib/src/test/java/com/auth0/jwt/impl/PayloadImplTest.java
Labels: CH: Changed, review:small

#542 Bump `jackson-databind` dependency to 2.13.2
  lib/build.gradle
Labels: CH: Security, dependencies, review:tiny

#546 Release 3.19.0
  CHANGELOG.md
  README.md
Labels: review:tiny

#538 [SDK-3186] Support date/time custom claim validation
  lib/src/main/java/com/auth0/jwt/JWTVerifier.java
  lib/src/main/java/com/auth0/jwt/interfaces/Verification.java
  lib/src/test/java/com/auth0/jwt/JWTVerifierTest.java
  lib/src/test/java/com/auth0/jwt/interfaces/VerificationTest.java
Labels: CH: Added, CH: Fixed, review:medium

#551 Undeprecate Single Key Constructor for Algorithms
  lib/src/main/java/com/auth0/jwt/algorithms/Algorithm.java
Labels: CH: Changed, review:small

#550 Update documentation and undeprecate single content sign methods
  lib/src/main/java/com/auth0/jwt/algorithms/Algorithm.java
  lib/src/main/java/com/auth0/jwt/algorithms/CryptoHelper.java
  lib/src/main/java/com/auth0/jwt/algorithms/ECDSAAlgorithm.java
  lib/src/main/java/com/auth0/jwt/algorithms/HMACAlgorithm.java
  lib/src/main/java/com/auth0/jwt/algorithms/NoneAlgorithm.java
  lib/src/main/java/com/auth0/jwt/algorithms/RSAAlgorithm.java
Labels: CH: Changed, review:small

#549 [SDK-3171] Fix header claims serialization
  lib/src/main/java/com/auth0/jwt/JWTCreator.java
  lib/src/main/java/com/auth0/jwt/impl/ClaimsHolder.java
  lib/src/main/java/com/auth0/jwt/impl/ClaimsSerializer.java
  lib/src/main/java/com/auth0/jwt/impl/HeaderClaimsHolder.java
  lib/src/main/java/com/auth0/jwt/impl/HeaderSerializer.java
  lib/src/main/java/com/auth0/jwt/impl/PayloadClaimsHolder.java
  lib/src/main/java/com/auth0/jwt/impl/PayloadSerializer.java
  lib/src/test/java/com/auth0/jwt/JWTCreatorTest.java
  lib/src/test/java/com/auth0/jwt/JWTDecoderTest.java
  lib/src/test/java/com/auth0/jwt/impl/PayloadClaimsHolderTest.java
  lib/src/test/java/com/auth0/jwt/impl/PayloadSerializerTest.java
Labels: CH: Breaking Change, review:medium

#553 [SDK-3212] Remove impl package export in module-info
  lib/src/main/java/module-info.java
Labels: CH: Removed, CH: Breaking Change, review:small

#555 Fix #554: Using a private key when validating JWT
  README.md
Labels: CH: Fixed, review:tiny

#556 Remove ES256K support
  lib/build.gradle
  lib/src/main/java/com/auth0/jwt/algorithms/Algorithm.java
  lib/src/test/java/com/auth0/jwt/ConcurrentVerifyTest.java
  lib/src/test/java/com/auth0/jwt/JWTCreatorTest.java
  lib/src/test/java/com/auth0/jwt/JWTTest.java
  lib/src/test/java/com/auth0/jwt/algorithms/AlgorithmTest.java
  lib/src/test/java/com/auth0/jwt/algorithms/ECDSAAlgorithmTest.java
  lib/src/test/java/com/auth0/jwt/algorithms/ECDSABouncyCastleProviderTests.java
  lib/src/test/resources/ec256k-key-private.pem
  lib/src/test/resources/ec256k-key-public-invalid.pem
  lib/src/test/resources/ec256k-key-public.pem
Labels: CH: Removed, CH: Breaking Change, review:medium

#561 Add lint checks
  config/checkstyle/checkstyle.xml
  lib/build.gradle
  lib/src/main/java/com/auth0/jwt/JWT.java
  lib/src/main/java/com/auth0/jwt/JWTCreator.java
  lib/src/main/java/com/auth0/jwt/JWTDecoder.java
  lib/src/main/java/com/auth0/jwt/JWTVerifier.java
  lib/src/main/java/com/auth0/jwt/TokenUtils.java
  lib/src/main/java/com/auth0/jwt/algorithms/Algorithm.java
  lib/src/main/java/com/auth0/jwt/algorithms/CryptoHelper.java
  lib/src/main/java/com/auth0/jwt/algorithms/ECDSAAlgorithm.java
  lib/src/main/java/com/auth0/jwt/algorithms/HMACAlgorithm.java
  lib/src/main/java/com/auth0/jwt/algorithms/NoneAlgorithm.java
  lib/src/main/java/com/auth0/jwt/algorithms/RSAAlgorithm.java
  lib/src/main/java/com/auth0/jwt/exceptions/AlgorithmMismatchException.java
  lib/src/main/java/com/auth0/jwt/exceptions/InvalidClaimException.java
  lib/src/main/java/com/auth0/jwt/exceptions/JWTCreationException.java
  lib/src/main/java/com/auth0/jwt/exceptions/JWTDecodeException.java
  lib/src/main/java/com/auth0/jwt/exceptions/JWTVerificationException.java
  lib/src/main/java/com/auth0/jwt/exceptions/SignatureGenerationException.java
  lib/src/main/java/com/auth0/jwt/exceptions/SignatureVerificationException.java
  lib/src/main/java/com/auth0/jwt/exceptions/TokenExpiredException.java
  lib/src/main/java/com/auth0/jwt/impl/BasicHeader.java
  lib/src/main/java/com/auth0/jwt/impl/ClaimsSerializer.java
  lib/src/main/java/com/auth0/jwt/impl/HeaderDeserializer.java
  lib/src/main/java/com/auth0/jwt/impl/JWTParser.java
  lib/src/main/java/com/auth0/jwt/impl/JsonNodeClaim.java
  lib/src/main/java/com/auth0/jwt/impl/NullClaim.java
  lib/src/main/java/com/auth0/jwt/impl/PayloadDeserializer.java
  lib/src/main/java/com/auth0/jwt/impl/PayloadImpl.java
  lib/src/main/java/com/auth0/jwt/impl/PayloadSerializer.java
  lib/src/main/java/com/auth0/jwt/impl/PublicClaims.java
  lib/src/main/java/com/auth0/jwt/interfaces/Claim.java
  lib/src/main/java/com/auth0/jwt/interfaces/JWTPartsParser.java
  lib/src/main/java/com/auth0/jwt/interfaces/JWTVerifier.java
  lib/src/main/java/com/auth0/jwt/interfaces/KeyProvider.java
  lib/src/main/java/com/auth0/jwt/interfaces/Verification.java
  lib/src/test/java/com/auth0/jwt/interfaces/ClaimTest.java
Labels: CH: Added, review:large

#562 [SDK-3155] Predicate based Claim verification
  lib/src/main/java/com/auth0/jwt/JWTVerifier.java
  lib/src/main/java/com/auth0/jwt/interfaces/Verification.java
  lib/src/test/java/com/auth0/jwt/JWTVerifierTest.java
  lib/src/test/java/com/auth0/jwt/interfaces/VerificationTest.java
Labels: CH: Added, review:large

#564 [SDK-3158] Null claim handling
  lib/src/main/java/com/auth0/jwt/JWTCreator.java
  lib/src/main/java/com/auth0/jwt/JWTVerifier.java
  lib/src/main/java/com/auth0/jwt/impl/JsonNodeClaim.java
  lib/src/main/java/com/auth0/jwt/impl/NullClaim.java
  lib/src/main/java/com/auth0/jwt/interfaces/Claim.java
  lib/src/main/java/com/auth0/jwt/interfaces/Verification.java
  lib/src/test/java/com/auth0/jwt/JWTCreatorTest.java
  lib/src/test/java/com/auth0/jwt/JWTDecoderTest.java
  lib/src/test/java/com/auth0/jwt/JWTVerifierTest.java
  lib/src/test/java/com/auth0/jwt/impl/BasicHeaderTest.java
  lib/src/test/java/com/auth0/jwt/impl/JsonNodeClaimTest.java
  lib/src/test/java/com/auth0/jwt/impl/NullClaimTest.java
  lib/src/test/java/com/auth0/jwt/impl/PayloadImplTest.java
  lib/src/test/java/com/auth0/jwt/interfaces/ClaimTest.java
  lib/src/test/java/com/auth0/jwt/interfaces/VerificationTest.java
Labels: CH: Changed, review:large

#568 [SDK-3154] Improved Exception Handling
  lib/src/main/java/com/auth0/jwt/JWTVerifier.java
  lib/src/main/java/com/auth0/jwt/exceptions/IncorrectClaimException.java
  lib/src/main/java/com/auth0/jwt/exceptions/InvalidClaimException.java
  lib/src/main/java/com/auth0/jwt/exceptions/MissingClaimException.java
  lib/src/main/java/com/auth0/jwt/exceptions/TokenExpiredException.java
  lib/src/main/java/com/auth0/jwt/impl/JsonNodeClaim.java
  lib/src/test/java/com/auth0/jwt/JWTVerifierTest.java
  lib/src/test/java/com/auth0/jwt/impl/JsonNodeClaimTest.java
  lib/src/test/java/com/auth0/jwt/matchers/CustomMatchers.java
Labels: CH: Added, review:large

#569 Release 3.19.1
  CHANGELOG.md
  README.md
Labels: review:tiny
