Repository auth0/java-jwt, pull requests merged in 2022-04, with the labels that each got.

#573 [SDK-3231] Added support for multiple checks on a single claim
  lib/src/main/java/com/auth0/jwt/JWTVerifier.java
  lib/src/main/java/com/auth0/jwt/impl/ExpectedCheckHolder.java
  lib/src/test/java/com/auth0/jwt/JWTVerifierTest.java
Labels: CH: Added, CH: Breaking Change, review:large

#575 Add Semgrep to continuous integration tests
  .circleci/config.yml
Labels: review:tiny

#571 Improved README structure
  README.md
Labels: CH: Added, review:medium

#577 [SDK-3159] JavaDoc updated
  lib/src/main/java/com/auth0/jwt/HeaderParams.java
  lib/src/main/java/com/auth0/jwt/JWT.java
  lib/src/main/java/com/auth0/jwt/JWTVerifier.java
  lib/src/main/java/com/auth0/jwt/RegisteredClaims.java
  lib/src/main/java/com/auth0/jwt/impl/PayloadSerializer.java
  lib/src/main/java/com/auth0/jwt/interfaces/Claim.java
  lib/src/main/java/com/auth0/jwt/interfaces/Header.java
  lib/src/main/java/com/auth0/jwt/interfaces/JWTPartsParser.java
  lib/src/main/java/com/auth0/jwt/interfaces/JWTVerifier.java
  lib/src/main/java/com/auth0/jwt/interfaces/KeyProvider.java
  lib/src/main/java/com/auth0/jwt/interfaces/Payload.java
  lib/src/main/java/com/auth0/jwt/interfaces/Verification.java
  lib/src/test/java/com/auth0/jwt/interfaces/VerificationTest.java
Labels: documentation, CH: Added, review:medium

#576 [SDK-3244] Add Migration Guide
  MIGRATION_GUIDE.md
Labels: documentation, CH: Added, review:medium
